# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  init:
    cmds:
      - go mod download
    preconditions:
      - &go test -x $(command -v go)

  build:tenancy:
    cmds:
      - go build -o out/bin/tenancy ./cmd/tenancy/tenancy.go
    preconditions:
      - *go

  default:
    cmds:
      - task build:tenancy
    silent: true
