version: '3'

vars:
  PROJECT_DIR: './'
  OUT_DIR: '{{.PROJECT_DIR}}/out'
  OUT_BIN_DIR: '{{.OUT_DIR}}/bin'

tasks:
  vendor:
    cmds:
      - go mod vendor
    preconditions:
      - &go test -x $(command -v go)
      - *go

  build:server:
    cmds:
      - go build -o {{.OUT_BIN_DIR}}/tenancy ./cmd/tenancy/tenancy.go
    preconditions:
      - *go

  run:server:
    cmds:
      - go run ./cmd/tenancy/tenancy.go
    preconditions:
      - *go

