# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:tenancy:
    cmds:
      - go build -o out/bin/tenancy ./cmd/tenancy/tenancy.go
    preconditions:
      - test -x $(command -v go)

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
